### ISSUE TITLE
Bindgen version used by wasm3-sys on crates.io doesn't match the source code

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasm3/wasm3-rs#32]
This repository's source code [says it uses `bindgen v0.59`](https://github.com/wasm3/wasm3-rs/blob/ccbb7112623a999340e32886ea6aa624be631374/wasm3-sys/Cargo.toml#L28), but the version on crates.io uses `bindgen v0.54.0`.

I'm not quite sure how that happened when the commit bumping the `bindgen` version literally says "Released 0.2.0" and we're on 0.3.0 now, but would you be able to release a new version of `wasm3-sys` so the dependencies line up?

At the moment I'm having issues because another dependency uses the latest `bindgen` version (v0.59.1) and the two `bindgen` versions are causing a link conflict with `clang-sys`.

**Comment by Veykril** [comment]
Ah ye I only bumped the `wasm3` version, not `wasm3-sys` so while the repo uses 0.59 the crates.io crate still uses the old version.

I'll look into that later today.

**Comment by Veykril** [comment]
On another note it might make sense to just remove bindgen from the build script entirely and build the the bindings once and ship them that way, will have to check if any item signatures exposed depend on conditional compilation.

**Comment by Veykril** [comment]
Synced the minor versions now(for clarity), uploaded `wasm3@0.3.1` which now uses `wasm3-sys@0.3.0` which uses bindgen 0.59.
