### ISSUE TITLE
How to call host functions in wasm3 rust api?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3-rs#44]
In the following wat file : 
[test.txt](https://github.com/wasm3/wasm3/files/9228835/test.txt)

It wants to call the function `assert_eq_i32` and `print_input` from host, how to call the host functions in wasm3 by rust api ?

**Comment by vshymanskyy** [comment]
I think the relevant example is this: https://github.com/wasm3/wasm3-rs/blob/df74c2a17ed8831595de43db98c406da4633e32a/examples/wasm_link.rs#L19
